// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WarehouseInventory.DB.Entities;

public partial class Stock
{
    public int Id { get; set; }

    public int ProductId { get; set; }

    public decimal Quantity { get; set; }

    public DateTime RestockedAt { get; set; }

    public string Location { get; set; }

    public virtual Product Product { get; set; }
}