services:
  redis:
    image: redis:latest
    container_name: warehouse_inventory_redis
    ports:
      - "63790:6379"
    volumes:
      - warehouse_inventory_redis_data:/data
    restart: always

volumes:
  warehouse_inventory_redis_data:
    driver: local